import strategies_package as st
from types import ModuleType
from typing import Any
from datetime import datetime, timedelta
from other_functions.date_and_time_functions import snap_date


def get_user_input() -> tuple[
    str,
    list[str],
    list[ModuleType],
    list[Any] | None,
    bool,
    list[tuple[datetime, datetime]]]:
    use_parallel_compute = True

    symbols: list[str] = [
        "BTCUSDT",
        "ETHUSDT",
        "BNBUSDT",
        "NEOUSDT",
        "LTCUSDT",
        "QTUMUSDT",
        "ADAUSDT",
        "XRPUSDT",
        "EOSUSDT",
        "IOTAUSDT",
        "XLMUSDT",
        "ONTUSDT",
        "TRXUSDT",
        "ETCUSDT",
        "ICXUSDT",
        "NULSUSDT",
        "VETUSDT",
        "LINKUSDT",
        "WAVESUSDT"
    ]

    strategies_list: list[ModuleType] = [
        st.A_aroon_fromInner_ct,
        st.A_aroon_fromInner_t,
        st.A_aroon_fromOuter_ct,
        st.A_aroon_fromOuter_t,
        st.A_aroon_htTrend_fromInner_ct,
        st.A_aroon_htTrend_fromInner_t,
        st.A_aroon_htTrend_fromOuter_ct,
        st.A_aroon_htTrend_fromOuter_t,
        st.A_aroon_linearReg_ct,
        st.A_aroon_linearReg_t,
        st.A_aroon_maBo_ct,
        st.A_aroon_maBo_t,
        st.A_aroon_trix_ct,
        st.A_aroon_trix_t,
        st.A_aroon_tsf_ct,
        st.A_aroon_tsf_t,
        st.B_adosc__ct,
        st.B_adosc__t,
        st.B_adosc_linearReg_ct,
        st.B_adosc_linearReg_t,
        st.B_adosc_maBo_ct,
        st.B_adosc_maBo_t,
        st.B_adosc_tsf_ct,
        st.B_adosc_tsf_t,
        st.B_mfi_fromInner_ct,
        st.B_mfi_fromInner_t,
        st.B_mfi_fromOuter_ct,
        st.B_mfi_fromOuter_t,
        st.B_mfi_linearReg_ct,
        st.B_mfi_linearReg_t,
        st.B_mfi_trix_ct,
        st.B_mfi_trix_t,
        st.B_mfi_tsf_ct,
        st.B_mfi_tsf_t,
        st.B_obv_breakout_ct,
        st.B_obv_breakout_t,
        st.B_obv_linearReg_ct,
        st.B_obv_linearReg_t,
        st.B_obv_maBo_ct,
        st.B_obv_maBo_t,
        st.B_obv_tsf_ct,
        st.B_obv_tsf_t,
        st.C_bop__ct,
        st.C_bop__t,
        st.C_bop_count_ct,
        st.C_bop_count_t,
        st.C_bop_linearReg_ct,
        st.C_bop_linearReg_t,
        st.C_bop_maCross_ct,
        st.C_bop_maCross_t,
        st.C_bop_posMinusNeg_ct,
        st.C_bop_posMinusNeg_t,
        st.C_bop_trix_ct,
        st.C_bop_trix_t,
        st.C_bop_tsf_ct,
        st.C_bop_tsf_t,
        st.D_adx__ct,
        st.D_adx__t,
        st.D_adx_linearReg_ct,
        st.D_adx_linearReg_t,
        st.D_adx_ma_ct,
        st.D_adx_ma_t,
        st.D_adx_trix_ct,
        st.D_adx_trix_t,
        st.D_adx_tsf_ct,
        st.D_adx_tsf_t,
        st.D_bollingerBreakout_fromInner_ct,
        st.D_bollingerBreakout_fromInner_t,
        st.D_bollingerBreakout_fromOuter_ct,
        st.D_bollingerBreakout_fromOuter_t,
        st.D_breakoutHighLow_ct,
        st.D_breakoutHighLow_t,
        st.D_breakout__ct,
        st.D_breakout__t,
        st.D_breakout_avg_ct,
        st.D_breakout_avg_t,
        st.D_breakout_med_ct,
        st.D_breakout_med_t,
        st.D_breakout_typical_ct,
        st.D_breakout_typical_t,
        st.D_breakout_wclprice_ct,
        st.D_breakout_wclprice_t,
        st.D_dynamic_ct,
        st.D_dynamic_t,
        st.D_htTrend_breakout_ct,
        st.D_htTrend_breakout_t,
        st.D_keltnerBreakout_fromInner_ct,
        st.D_keltnerBreakout_fromInner_t,
        st.D_keltnerBreakout_fromOuter_ct,
        st.D_keltnerBreakout_fromOuter_t,
        st.D_stdev_ma_ct,
        st.D_stdev_ma_t,
        st.D_tsf_breakout_ct,
        st.D_tsf_breakout_t,
        st.D_turtle_ct,
        st.D_turtle_t,
        st.E_cci_fromInner_ct,
        st.E_cci_fromInner_t,
        st.E_cci_fromOuter_ct,
        st.E_cci_fromOuter_t,
        st.E_cci_htTrend_fromInner_ct,
        st.E_cci_htTrend_fromInner_t,
        st.E_cci_htTrend_fromOuter_ct,
        st.E_cci_htTrend_fromOuter_t,
        st.E_cci_linearReg_ct,
        st.E_cci_linearReg_t,
        st.E_cci_maBo_ct,
        st.E_cci_maBo_t,
        st.E_cci_tsf_ct,
        st.E_cci_tsf_t,
        st.F_cmo_fromInner_ct,
        st.F_cmo_fromInner_t,
        st.F_cmo_fromOuter_ct,
        st.F_cmo_fromOuter_t,
        st.F_cmo_htTrend_fromInner_ct,
        st.F_cmo_htTrend_fromInner_t,
        st.F_cmo_htTrend_fromOuter_ct,
        st.F_cmo_htTrend_fromOuter_t,
        st.F_cmo_linearReg_ct,
        st.F_cmo_linearReg_t,
        st.F_cmo_maBo__ct,
        st.F_cmo_maBo__t,
        st.F_cmo_maBo_avg_ct,
        st.F_cmo_maBo_avg_t,
        st.F_cmo_maBo_med_ct,
        st.F_cmo_maBo_med_t,
        st.F_cmo_maBo_typical_ct,
        st.F_cmo_maBo_typical_t,
        st.F_cmo_maBo_wclprice_ct,
        st.F_cmo_maBo_wclprice_t,
        st.F_cmo_tsf_ct,
        st.F_cmo_tsf_t,
        st.G_adx_dm_ct,
        st.G_adx_dm_t,
        st.G_adx_linearReg_dm_ct,
        st.G_adx_linearReg_dm_t,
        st.G_adx_trix_dm_ct,
        st.G_adx_trix_dm_t,
        st.G_dm__ct,
        st.G_dm__t,
        st.G_dm_htTrend_ct,
        st.G_dm_htTrend_t,
        st.G_dm_linearReg_ct,
        st.G_dm_linearReg_t,
        st.G_dm_trix_ct,
        st.G_dm_trix_t,
        st.G_dm_tsf_ct,
        st.G_dm_tsf_t,
        st.H_hilbertSine__ct,
        st.H_hilbertSine__t,
        st.H_hilbertSine_avg_ct,
        st.H_hilbertSine_avg_t,
        st.H_hilbertSine_med_ct,
        st.H_hilbertSine_med_t,
        st.H_hilbertSine_typical_ct,
        st.H_hilbertSine_typical_t,
        st.H_hilbertSine_wclprice_ct,
        st.H_hilbertSine_wclprice_t,
        st.H_hilbertTrendMode_ct,
        st.H_hilbertTrendMode_t,
        st.H_hilbertTrend__ct,
        st.H_hilbertTrend__t,
        st.H_hilbertTrend_avg_ct,
        st.H_hilbertTrend_avg_t,
        st.H_hilbertTrend_linearReg_ct,
        st.H_hilbertTrend_linearReg_t,
        st.H_hilbertTrend_med_ct,
        st.H_hilbertTrend_med_t,
        st.H_hilbertTrend_trix_ct,
        st.H_hilbertTrend_trix_t,
        st.H_hilbertTrend_tsf_ct,
        st.H_hilbertTrend_tsf_t,
        st.H_hilbertTrend_typical_ct,
        st.H_hilbertTrend_typical_t,
        st.H_hilbertTrend_wclprice_ct,
        st.H_hilbertTrend_wclprice_t,
        st.I_maBoDiff_breakout_ct,
        st.I_maBoDiff_breakout_t,
        st.I_maBoDiff_linearReg_ct,
        st.I_maBoDiff_linearReg_t,
        st.I_maBoDiff_tsf_ct,
        st.I_maBoDiff_tsf_t,
        st.I_maBo__ct,
        st.I_maBo__t,
        st.I_maBo_avg_ct,
        st.I_maBo_avg_t,
        st.I_maBo_dema_ct,
        st.I_maBo_dema_t,
        st.I_maBo_ema_ct,
        st.I_maBo_ema_t,
        st.I_maBo_kama_ct,
        st.I_maBo_kama_t,
        st.I_maBo_mama_ct,
        st.I_maBo_mama_t,
        st.I_maBo_med_ct,
        st.I_maBo_med_t,
        st.I_maBo_midprice_ct,
        st.I_maBo_midprice_t,
        st.I_maBo_tema_ct,
        st.I_maBo_tema_t,
        st.I_maBo_trima_ct,
        st.I_maBo_trima_t,
        st.I_maBo_typical_ct,
        st.I_maBo_typical_t,
        st.I_maBo_wclprice_ct,
        st.I_maBo_wclprice_t,
        st.I_maBo_wma_ct,
        st.I_maBo_wma_t,
        st.J_linearReg__ct,
        st.J_linearReg__t,
        st.J_linearReg_avg_ct,
        st.J_linearReg_avg_t,
        st.J_linearReg_linearReg_ct,
        st.J_linearReg_linearReg_t,
        st.J_linearReg_maBo_ct,
        st.J_linearReg_maBo_t,
        st.J_linearReg_med_ct,
        st.J_linearReg_med_t,
        st.J_linearReg_trix_ct,
        st.J_linearReg_trix_t,
        st.J_linearReg_tsf_ct,
        st.J_linearReg_tsf_t,
        st.J_linearReg_typical_ct,
        st.J_linearReg_typical_t,
        st.J_linearReg_wclprice_ct,
        st.J_linearReg_wclprice_t,
        st.K_macd__ct,
        st.K_macd__t,
        st.K_macd_avg_ct,
        st.K_macd_avg_t,
        st.K_macd_breakout_ct,
        st.K_macd_breakout_t,
        st.K_macd_linearRegSignal_ct,
        st.K_macd_linearRegSignal_t,
        st.K_macd_linearReg_ct,
        st.K_macd_linearReg_t,
        st.K_macd_med_ct,
        st.K_macd_med_t,
        st.K_macd_tsf_ct,
        st.K_macd_tsf_t,
        st.K_macd_typical_ct,
        st.K_macd_typical_t,
        st.K_macd_wclprice_ct,
        st.K_macd_wclprice_t,
        st.L_maCross__ct,
        st.L_maCross__t,
        st.L_maCross_avg_ct,
        st.L_maCross_avg_t,
        st.L_maCross_dema_ct,
        st.L_maCross_dema_t,
        st.L_maCross_ema_ct,
        st.L_maCross_ema_t,
        st.L_maCross_kama_ct,
        st.L_maCross_kama_t,
        st.L_maCross_mama_ct,
        st.L_maCross_mama_t,
        st.L_maCross_med_ct,
        st.L_maCross_med_t,
        st.L_maCross_midprice_ct,
        st.L_maCross_midprice_t,
        st.L_maCross_tema_ct,
        st.L_maCross_tema_t,
        st.L_maCross_trima_ct,
        st.L_maCross_trima_t,
        st.L_maCross_typical_ct,
        st.L_maCross_typical_t,
        st.L_maCross_wclprice_ct,
        st.L_maCross_wclprice_t,
        st.L_maCross_wma_ct,
        st.L_maCross_wma_t,
        st.M_rsi_fromInner_ct,
        st.M_rsi_fromInner_t,
        st.M_rsi_fromOuter_ct,
        st.M_rsi_fromOuter_t,
        st.M_rsi_linearReg__ct,
        st.M_rsi_linearReg__t,
        st.M_rsi_linearReg_avg_ct,
        st.M_rsi_linearReg_avg_t,
        st.M_rsi_linearReg_med_ct,
        st.M_rsi_linearReg_med_t,
        st.M_rsi_linearReg_typical_ct,
        st.M_rsi_linearReg_typical_t,
        st.M_rsi_linearReg_wclprice_ct,
        st.M_rsi_linearReg_wclprice_t,
        st.M_rsi_maBo_ct,
        st.M_rsi_maBo_t,
        st.M_rsi_trix_ct,
        st.M_rsi_trix_t,
        st.M_rsi_tsf_ct,
        st.M_rsi_tsf_t,
        st.N_sar__ct,
        st.N_sar__t,
        st.N_sar_avg_ct,
        st.N_sar_avg_t,
        st.N_sar_close_ct,
        st.N_sar_close_t,
        st.N_sar_htTrend_ct,
        st.N_sar_htTrend_t,
        st.N_sar_med_ct,
        st.N_sar_med_t,
        st.N_sar_typical_ct,
        st.N_sar_typical_t,
        st.N_sar_wclprice_ct,
        st.N_sar_wclprice_t,
        st.O_spike__ct,
        st.O_spike__t,
        st.O_spike_atr_ct,
        st.O_spike_atr_t,
        st.O_spike_avg_ct,
        st.O_spike_avg_t,
        st.O_spike_maxAtr__ct,
        st.O_spike_maxAtr__t,
        st.O_spike_maxAtr_avg_ct,
        st.O_spike_maxAtr_avg_t,
        st.O_spike_maxAtr_med_ct,
        st.O_spike_maxAtr_med_t,
        st.O_spike_maxAtr_typical_ct,
        st.O_spike_maxAtr_typical_t,
        st.O_spike_maxAtr_wclprice_ct,
        st.O_spike_maxAtr_wclprice_t,
        st.O_spike_maxTr_ct,
        st.O_spike_maxTr_t,
        st.O_spike_max_ct,
        st.O_spike_max_t,
        st.O_spike_med_ct,
        st.O_spike_med_t,
        st.O_spike_typical_ct,
        st.O_spike_typical_t,
        st.O_spike_wclprice_ct,
        st.O_spike_wclprice_t,
        st.P_stoch__ct,
        st.P_stoch__t,
        st.P_stoch_fromInner_ct,
        st.P_stoch_fromInner_t,
        st.P_stoch_fromOuter_ct,
        st.P_stoch_fromOuter_t,
        st.P_stoch_linearReg_ct,
        st.P_stoch_linearReg_t,
        st.P_stoch_maBo_ct,
        st.P_stoch_maBo_t,
        st.P_stoch_thresh_ct,
        st.P_stoch_thresh_t,
        st.P_stoch_trix_ct,
        st.P_stoch_trix_t,
        st.P_stoch_tsf_ct,
        st.P_stoch_tsf_t,
        st.Q_stochrsi__ct,
        st.Q_stochrsi__t,
        st.Q_stochrsi_fromInner_ct,
        st.Q_stochrsi_fromInner_t,
        st.Q_stochrsi_fromOuter_ct,
        st.Q_stochrsi_fromOuter_t,
        st.Q_stochrsi_linearReg_ct,
        st.Q_stochrsi_linearReg_t,
        st.Q_stochrsi_maBo_ct,
        st.Q_stochrsi_maBo_t,
        st.Q_stochrsi_thresh_ct,
        st.Q_stochrsi_thresh_t,
        st.Q_stochrsi_trix_ct,
        st.Q_stochrsi_trix_t,
        st.Q_stochrsi_tsf_ct,
        st.Q_stochrsi_tsf_t,
        st.R_tailbarClose__ct,
        st.R_tailbarClose__t,
        st.R_tailbarClose_linearReg_ct,
        st.R_tailbarClose_linearReg_t,
        st.R_tailbarClose_maBo_ct,
        st.R_tailbarClose_maBo_t,
        st.R_tailbarClose_trix_ct,
        st.R_tailbarClose_trix_t,
        st.R_tailbarClose_tsf_ct,
        st.R_tailbarClose_tsf_t,
        st.R_tailbar__ct,
        st.R_tailbar__t,
        st.R_tailbar_linearReg_ct,
        st.R_tailbar_linearReg_t,
        st.R_tailbar_maBo_ct,
        st.R_tailbar_maBo_t,
        st.R_tailbar_trix_ct,
        st.R_tailbar_trix_t,
        st.R_tailbar_tsf_ct,
        st.R_tailbar_tsf_t,
        st.S_trendChange_bo_ct,
        st.S_trendChange_bo_t,
        st.S_trendChange_linearReg_ct,
        st.S_trendChange_linearReg_t,
        st.S_trendChange_maBo_ct,
        st.S_trendChange_maBo_t,
        st.S_trendChange_trix_ct,
        st.S_trendChange_trix_t,
        st.S_trendChange_tsf_ct,
        st.S_trendChange_tsf_t,
        st.S_trend__ct,
        st.S_trend__t,
        st.S_trend_avg_ct,
        st.S_trend_avg_t,
        st.S_trend_med_ct,
        st.S_trend_med_t,
        st.S_trend_typ_ct,
        st.S_trend_typ_t,
        st.S_trend_wclprice_ct,
        st.S_trend_wclprice_t,
        st.T_trix__ct,
        st.T_trix__t,
        st.T_trix_avg_ct,
        st.T_trix_avg_t,
        st.T_trix_bo_ct,
        st.T_trix_bo_t,
        st.T_trix_linearReg_ct,
        st.T_trix_linearReg_t,
        st.T_trix_maBo_ct,
        st.T_trix_maBo_t,
        st.T_trix_med_ct,
        st.T_trix_med_t,
        st.T_trix_tsf_ct,
        st.T_trix_tsf_t,
        st.T_trix_typical_ct,
        st.T_trix_typical_t,
        st.T_trix_wclprice_ct,
        st.T_trix_wclprice_t,
        st.U_tsf__ct,
        st.U_tsf__t,
        st.U_tsf_avg_ct,
        st.U_tsf_avg_t,
        st.U_tsf_linearReg_ct,
        st.U_tsf_linearReg_t,
        st.U_tsf_maBo_ct,
        st.U_tsf_maBo_t,
        st.U_tsf_med_ct,
        st.U_tsf_med_t,
        st.U_tsf_trix_ct,
        st.U_tsf_trix_t,
        st.U_tsf_typical_ct,
        st.U_tsf_typical_t,
        st.U_tsf_wclprice_ct,
        st.U_tsf_wclprice_t,
        st.V_ultimate_fromInner_ct,
        st.V_ultimate_fromInner_t,
        st.V_ultimate_fromOuter_ct,
        st.V_ultimate_fromOuter_t,
        st.V_ultimate_htTrend_fromInner_ct,
        st.V_ultimate_htTrend_fromInner_t,
        st.V_ultimate_htTrend_fromOuter_ct,
        st.V_ultimate_htTrend_fromOuter_t,
        st.V_ultimate_linearReg_ct,
        st.V_ultimate_linearReg_t,
        st.V_ultimate_maBo_ct,
        st.V_ultimate_maBo_t,
        st.V_ultimate_trix_ct,
        st.V_ultimate_trix_t,
        st.V_ultimate_tsf_ct,
        st.V_ultimate_tsf_t,
        st.W_willR_fromInner_ct,
        st.W_willR_fromInner_t,
        st.W_willR_fromOuter_ct,
        st.W_willR_fromOuter_t,
        st.W_willR_htTrend_fromInner_ct,
        st.W_willR_htTrend_fromInner_t,
        st.W_willR_htTrend_fromOuter_ct,
        st.W_willR_htTrend_fromOuter_t,
        st.W_willR_linearReg_ct,
        st.W_willR_linearReg_t,
        st.W_willR_maBo_ct,
        st.W_willR_maBo_t,
        st.W_willR_trix_ct,
        st.W_willR_trix_t,
        st.W_willR_tsf_ct,
        st.W_willR_tsf_t,
        st.Z_3InsideUpDown,
        st.Z_3LineStrike,
        st.Z_3Outside,
        st.Z_3whiteSoldiers,
        st.Z_abandonedBaby,
        st.Z_beltHold,
        st.Z_doji,
        st.Z_dragonFly,
        st.Z_engulfing,
        st.Z_hammer,
        st.Z_harami,
        st.Z_haramiCross,
        st.Z_highWave,
        st.Z_hikkake,
        st.Z_hikkakeMod,
        st.Z_longDoji,
        st.Z_longLine,
        st.Z_marubozu,
        st.Z_marubozuClosing,
        st.Z_richshawMan,
        st.Z_shortLine,
        st.Z_spinningTop,
        st.S_trendRolling__ct,
        st.S_trendRolling__t,
        st.S_trendRolling_avg_ct,
        st.S_trendRolling_avg_t,
        st.S_trendRolling_linearReg_ct,
        st.S_trendRolling_linearReg_t,
        st.S_trendRolling_maBo_ct,
        st.S_trendRolling_maBo_t,
        st.S_trendRolling_med_ct,
        st.S_trendRolling_med_t,
        st.S_trendRolling_trix_ct,
        st.S_trendRolling_trix_t,
        st.S_trendRolling_tsf_ct,
        st.S_trendRolling_tsf_t,
        st.S_trendRolling_typical_ct,
        st.S_trendRolling_typical_t,
        st.S_trendRolling_wclprice_ct,
        st.S_trendRolling_wclprice_t,
    ]

    strategies_list = [strat for strat in strategies_list if strat.__name__[-3:] != '_ct']

    routine: str = 'validation_phase'
    dates = [get_routine_dates(routine=routine)]

    """
    Example:
    combinations: list[Any] | None = [
        ('BTCUSDT', st.ma_cross_t),
        ('ETHUSDT', st.ma_cross_t2),
    ]
    """
    combinations: list[Any] | None = [
        ("BTCUSDT", st.A_aroon_fromInner_t),
        ("ETHUSDT", st.A_aroon_fromOuter_t),
        ("XRPUSDT", st.A_aroon_fromOuter_t),
        ("LINKUSDT", st.A_aroon_fromOuter_t),
        ("BTCUSDT", st.A_aroon_fromOuter_t),
        ("LTCUSDT", st.A_aroon_fromOuter_t),
        ("ADAUSDT", st.A_aroon_fromOuter_t),
        ("ETHUSDT", st.A_aroon_linearReg_t),
        ("XRPUSDT", st.A_aroon_maBo_t),
        ("LINKUSDT", st.A_aroon_maBo_t),
        ("XLMUSDT", st.A_aroon_maBo_t),
        ("LINKUSDT", st.A_aroon_trix_t),
        ("ADAUSDT", st.A_aroon_tsf_t),
        ("LTCUSDT", st.B_adosc__t),
        ("BTCUSDT", st.B_adosc_linearReg_t),
        ("ETHUSDT", st.B_adosc_linearReg_t),
        ("LINKUSDT", st.B_adosc_maBo_t),
        ("ETHUSDT", st.B_adosc_maBo_t),
        ("BTCUSDT", st.B_adosc_tsf_t),
        ("XRPUSDT", st.B_adosc_tsf_t),
        ("BTCUSDT", st.B_mfi_fromInner_t),
        ("ETHUSDT", st.B_mfi_fromInner_t),
        ("LTCUSDT", st.B_mfi_fromOuter_t),
        ("LINKUSDT", st.B_mfi_linearReg_t),
        ("XRPUSDT", st.B_mfi_linearReg_t),
        ("ADAUSDT", st.B_mfi_linearReg_t),
        ("ETHUSDT", st.B_mfi_linearReg_t),
        ("LINKUSDT", st.B_mfi_trix_t),
        ("ADAUSDT", st.B_mfi_trix_t),
        ("BTCUSDT", st.B_mfi_trix_t),
        ("ETHUSDT", st.B_obv_breakout_t),
        ("BTCUSDT", st.B_obv_breakout_t),
        ("ADAUSDT", st.B_obv_breakout_t),
        ("ETHUSDT", st.B_obv_linearReg_t),
        ("BTCUSDT", st.B_obv_linearReg_t),
        ("ADAUSDT", st.B_obv_maBo_t),
        ("LINKUSDT", st.B_obv_maBo_t),
        ("ETHUSDT", st.B_obv_tsf_t),
        ("ETHUSDT", st.C_bop__t),
        ("BTCUSDT", st.C_bop_posMinusNeg_t),
        ("ADAUSDT", st.C_bop_posMinusNeg_t),
        ("LINKUSDT", st.C_bop_trix_t),
        ("ETHUSDT", st.D_adx__t),
        ("BTCUSDT", st.D_adx__t),
        ("XRPUSDT", st.D_adx__t),
        ("LINKUSDT", st.D_adx__t),
        ("ETHUSDT", st.D_adx_linearReg_t),
        ("ADAUSDT", st.D_adx_linearReg_t),
        ("BTCUSDT", st.D_adx_linearReg_t),
        ("ETHUSDT", st.D_adx_ma_t),
        ("LINKUSDT", st.D_adx_ma_t),
        ("BTCUSDT", st.D_adx_ma_t),
        ("ADAUSDT", st.D_adx_ma_t),
        ("ETHUSDT", st.D_adx_trix_t),
        ("ETHUSDT", st.D_adx_tsf_t),
        ("BTCUSDT", st.D_adx_tsf_t),
        ("LINKUSDT", st.D_adx_tsf_t),
        ("XRPUSDT", st.D_adx_tsf_t),
        ("ETHUSDT", st.D_bollingerBreakout_fromInner_t),
        ("BTCUSDT", st.D_bollingerBreakout_fromInner_t),
        ("XRPUSDT", st.D_bollingerBreakout_fromInner_t),
        ("ADAUSDT", st.D_bollingerBreakout_fromInner_t),
        ("ETHUSDT", st.D_breakout__t),
        ("BTCUSDT", st.D_breakout__t),
        ("XRPUSDT", st.D_breakout__t),
        ("LINKUSDT", st.D_breakout__t),
        ("ADAUSDT", st.D_breakout__t),
        ("BTCUSDT", st.D_breakout_avg_t),
        ("LINKUSDT", st.D_breakout_avg_t),
        ("ETHUSDT", st.D_breakout_avg_t),
        ("XRPUSDT", st.D_breakout_avg_t),
        ("ADAUSDT", st.D_breakout_avg_t),
        ("ETHUSDT", st.D_breakout_med_t),
        ("ADAUSDT", st.D_breakout_med_t),
        ("BTCUSDT", st.D_breakout_med_t),
        ("XRPUSDT", st.D_breakout_med_t),
        ("LINKUSDT", st.D_breakout_med_t),
        ("XLMUSDT", st.D_breakout_med_t),
        ("BTCUSDT", st.D_breakout_typical_t),
        ("ETHUSDT", st.D_breakout_typical_t),
        ("ADAUSDT", st.D_breakout_typical_t),
        ("LINKUSDT", st.D_breakout_typical_t),
        ("XRPUSDT", st.D_breakout_typical_t),
        ("BTCUSDT", st.D_breakout_wclprice_t),
        ("LTCUSDT", st.D_breakout_wclprice_t),
        ("LINKUSDT", st.D_breakout_wclprice_t),
        ("ETHUSDT", st.D_breakout_wclprice_t),
        ("ADAUSDT", st.D_breakout_wclprice_t),
        ("XRPUSDT", st.D_breakout_wclprice_t),
        ("XLMUSDT", st.D_breakout_wclprice_t),
        ("ETHUSDT", st.D_breakoutHighLow_t),
        ("BTCUSDT", st.D_breakoutHighLow_t),
        ("XRPUSDT", st.D_breakoutHighLow_t),
        ("LINKUSDT", st.D_breakoutHighLow_t),
        ("XLMUSDT", st.D_breakoutHighLow_t),
        ("ADAUSDT", st.D_breakoutHighLow_t),
        ("ETHUSDT", st.D_dynamic_t),
        ("BTCUSDT", st.D_dynamic_t),
        ("LINKUSDT", st.D_dynamic_t),
        ("BTCUSDT", st.D_htTrend_breakout_t),
        ("ADAUSDT", st.D_htTrend_breakout_t),
        ("XRPUSDT", st.D_htTrend_breakout_t),
        ("ETHUSDT", st.D_keltnerBreakout_fromInner_t),
        ("ADAUSDT", st.D_keltnerBreakout_fromInner_t),
        ("BTCUSDT", st.D_keltnerBreakout_fromInner_t),
        ("XRPUSDT", st.D_keltnerBreakout_fromInner_t),
        ("ETHUSDT", st.D_stdev_ma_t),
        ("BTCUSDT", st.D_stdev_ma_t),
        ("XLMUSDT", st.D_stdev_ma_t),
        ("XRPUSDT", st.D_stdev_ma_t),
        ("ADAUSDT", st.D_stdev_ma_t),
        ("ETHUSDT", st.D_tsf_breakout_t),
        ("BTCUSDT", st.D_tsf_breakout_t),
        ("VETUSDT", st.D_tsf_breakout_t),
        ("ETHUSDT", st.E_cci_fromInner_t),
        ("XRPUSDT", st.E_cci_fromInner_t),
        ("BTCUSDT", st.E_cci_fromInner_t),
        ("BTCUSDT", st.E_cci_htTrend_fromInner_t),
        ("LTCUSDT", st.E_cci_htTrend_fromInner_t),
        ("XLMUSDT", st.E_cci_linearReg_t),
        ("BTCUSDT", st.F_cmo_fromInner_t),
        ("ETHUSDT", st.F_cmo_htTrend_fromInner_t),
        ("ADAUSDT", st.F_cmo_htTrend_fromInner_t),
        ("VETUSDT", st.F_cmo_htTrend_fromInner_t),
        ("BTCUSDT", st.F_cmo_htTrend_fromInner_t),
        ("ETHUSDT", st.F_cmo_htTrend_fromOuter_t),
        ("BTCUSDT", st.F_cmo_htTrend_fromOuter_t),
        ("LINKUSDT", st.F_cmo_linearReg_t),
        ("XLMUSDT", st.F_cmo_linearReg_t),
        ("XLMUSDT", st.F_cmo_maBo__t),
        ("LTCUSDT", st.F_cmo_maBo__t),
        ("LINKUSDT", st.F_cmo_maBo_avg_t),
        ("XRPUSDT", st.F_cmo_maBo_avg_t),
        ("ETHUSDT", st.F_cmo_maBo_avg_t),
        ("XLMUSDT", st.F_cmo_maBo_avg_t),
        ("LTCUSDT", st.F_cmo_maBo_avg_t),
        ("BTCUSDT", st.F_cmo_maBo_med_t),
        ("XRPUSDT", st.F_cmo_maBo_med_t),
        ("ETHUSDT", st.F_cmo_maBo_med_t),
        ("XLMUSDT", st.F_cmo_maBo_med_t),
        ("LTCUSDT", st.F_cmo_maBo_med_t),
        ("ETHUSDT", st.F_cmo_maBo_typical_t),
        ("BTCUSDT", st.F_cmo_maBo_typical_t),
        ("XLMUSDT", st.F_cmo_maBo_typical_t),
        ("LINKUSDT", st.F_cmo_maBo_typical_t),
        ("LTCUSDT", st.F_cmo_maBo_typical_t),
        ("LINKUSDT", st.F_cmo_maBo_wclprice_t),
        ("BTCUSDT", st.F_cmo_maBo_wclprice_t),
        ("XLMUSDT", st.F_cmo_maBo_wclprice_t),
        ("LTCUSDT", st.F_cmo_maBo_wclprice_t),
        ("ETHUSDT", st.F_cmo_tsf_t),
        ("BTCUSDT", st.F_cmo_tsf_t),
        ("ADAUSDT", st.G_adx_linearReg_dm_t),
        ("XLMUSDT", st.G_adx_linearReg_dm_t),
        ("LINKUSDT", st.G_adx_linearReg_dm_t),
        ("LINKUSDT", st.G_adx_trix_dm_t),
        ("ETHUSDT", st.G_adx_trix_dm_t),
        ("XLMUSDT", st.G_adx_trix_dm_t),
        ("ETHUSDT", st.G_dm__t),
        ("BTCUSDT", st.G_dm__t),
        ("LINKUSDT", st.G_dm_htTrend_t),
        ("ETHUSDT", st.G_dm_htTrend_t),
        ("XRPUSDT", st.G_dm_htTrend_t),
        ("XLMUSDT", st.G_dm_linearReg_t),
        ("LINKUSDT", st.G_dm_trix_t),
        ("ETHUSDT", st.G_dm_tsf_t),
        ("LINKUSDT", st.G_dm_tsf_t),
        ("XRPUSDT", st.G_dm_tsf_t),
        ("ETHUSDT", st.H_hilbertTrend__t),
        ("ADAUSDT", st.H_hilbertTrend__t),
        ("BTCUSDT", st.H_hilbertTrend__t),
        ("BTCUSDT", st.H_hilbertTrend_avg_t),
        ("ADAUSDT", st.H_hilbertTrend_avg_t),
        ("ETHUSDT", st.H_hilbertTrend_avg_t),
        ("BTCUSDT", st.H_hilbertTrend_linearReg_t),
        ("XRPUSDT", st.H_hilbertTrend_linearReg_t),
        ("ETHUSDT", st.H_hilbertTrend_linearReg_t),
        ("LINKUSDT", st.H_hilbertTrend_linearReg_t),
        ("BTCUSDT", st.H_hilbertTrend_med_t),
        ("ADAUSDT", st.H_hilbertTrend_med_t),
        ("XRPUSDT", st.H_hilbertTrend_med_t),
        ("BTCUSDT", st.H_hilbertTrend_trix_t),
        ("XLMUSDT", st.H_hilbertTrend_trix_t),
        ("XRPUSDT", st.H_hilbertTrend_trix_t),
        ("LINKUSDT", st.H_hilbertTrend_trix_t),
        ("ETHUSDT", st.H_hilbertTrend_trix_t),
        ("LINKUSDT", st.H_hilbertTrend_tsf_t),
        ("ETHUSDT", st.H_hilbertTrend_typical_t),
        ("ADAUSDT", st.H_hilbertTrend_typical_t),
        ("BTCUSDT", st.H_hilbertTrend_typical_t),
        ("XRPUSDT", st.H_hilbertTrend_typical_t),
        ("ETHUSDT", st.H_hilbertTrend_wclprice_t),
        ("ADAUSDT", st.H_hilbertTrend_wclprice_t),
        ("BTCUSDT", st.H_hilbertTrend_wclprice_t),
        ("XRPUSDT", st.H_hilbertTrend_wclprice_t),
        ("BTCUSDT", st.H_hilbertTrendMode_t),
        ("XRPUSDT", st.H_hilbertTrendMode_t),
        ("ETHUSDT", st.I_maBo__t),
        ("BTCUSDT", st.I_maBo__t),
        ("ETHUSDT", st.I_maBo_avg_t),
        ("BTCUSDT", st.I_maBo_avg_t),
        ("ETHUSDT", st.I_maBo_dema_t),
        ("BTCUSDT", st.I_maBo_ema_t),
        ("ETHUSDT", st.I_maBo_ema_t),
        ("XRPUSDT", st.I_maBo_kama_t),
        ("BTCUSDT", st.I_maBo_kama_t),
        ("ETHUSDT", st.I_maBo_kama_t),
        ("ETHUSDT", st.I_maBo_med_t),
        ("BTCUSDT", st.I_maBo_med_t),
        ("BTCUSDT", st.I_maBo_midprice_t),
        ("ETHUSDT", st.I_maBo_midprice_t),
        ("ETHUSDT", st.I_maBo_trima_t),
        ("BTCUSDT", st.I_maBo_trima_t),
        ("ADAUSDT", st.I_maBo_trima_t),
        ("XRPUSDT", st.I_maBo_trima_t),
        ("ETHUSDT", st.I_maBo_typical_t),
        ("BTCUSDT", st.I_maBo_typical_t),
        ("ETHUSDT", st.I_maBo_wclprice_t),
        ("BTCUSDT", st.I_maBo_wclprice_t),
        ("BTCUSDT", st.I_maBo_wma_t),
        ("ETHUSDT", st.I_maBoDiff_breakout_t),
        ("ADAUSDT", st.I_maBoDiff_breakout_t),
        ("XRPUSDT", st.I_maBoDiff_breakout_t),
        ("BTCUSDT", st.I_maBoDiff_tsf_t),
        ("ETHUSDT", st.I_maBoDiff_tsf_t),
        ("BTCUSDT", st.J_linearReg__t),
        ("ETHUSDT", st.J_linearReg__t),
        ("BTCUSDT", st.J_linearReg_avg_t),
        ("ETHUSDT", st.J_linearReg_avg_t),
        ("BTCUSDT", st.J_linearReg_med_t),
        ("LINKUSDT", st.J_linearReg_trix_t),
        ("ADAUSDT", st.J_linearReg_tsf_t),
        ("LINKUSDT", st.J_linearReg_tsf_t),
        ("XRPUSDT", st.J_linearReg_tsf_t),
        ("BTCUSDT", st.J_linearReg_typical_t),
        ("ETHUSDT", st.J_linearReg_typical_t),
        ("BTCUSDT", st.J_linearReg_wclprice_t),
        ("ETHUSDT", st.J_linearReg_wclprice_t),
        ("ETHUSDT", st.K_macd__t),
        ("LTCUSDT", st.K_macd__t),
        ("XRPUSDT", st.K_macd__t),
        ("BTCUSDT", st.K_macd__t),
        ("LINKUSDT", st.K_macd__t),
        ("ETHUSDT", st.K_macd_avg_t),
        ("LTCUSDT", st.K_macd_avg_t),
        ("BTCUSDT", st.K_macd_avg_t),
        ("LINKUSDT", st.K_macd_avg_t),
        ("XLMUSDT", st.K_macd_breakout_t),
        ("XLMUSDT", st.K_macd_linearReg_t),
        ("XRPUSDT", st.K_macd_linearRegSignal_t),
        ("LINKUSDT", st.K_macd_linearRegSignal_t),
        ("XLMUSDT", st.K_macd_linearRegSignal_t),
        ("ETHUSDT", st.K_macd_linearRegSignal_t),
        ("ETHUSDT", st.K_macd_med_t),
        ("BTCUSDT", st.K_macd_med_t),
        ("XRPUSDT", st.K_macd_med_t),
        ("LINKUSDT", st.K_macd_med_t),
        ("LTCUSDT", st.K_macd_med_t),
        ("ADAUSDT", st.K_macd_tsf_t),
        ("ETHUSDT", st.K_macd_typical_t),
        ("LTCUSDT", st.K_macd_typical_t),
        ("BTCUSDT", st.K_macd_typical_t),
        ("LINKUSDT", st.K_macd_typical_t),
        ("ETHUSDT", st.K_macd_wclprice_t),
        ("LTCUSDT", st.K_macd_wclprice_t),
        ("BTCUSDT", st.K_macd_wclprice_t),
        ("LINKUSDT", st.K_macd_wclprice_t),
        ("XRPUSDT", st.K_macd_wclprice_t),
        ("BTCUSDT", st.L_maCross__t),
        ("ADAUSDT", st.L_maCross__t),
        ("LINKUSDT", st.L_maCross__t),
        ("BTCUSDT", st.L_maCross_avg_t),
        ("ETHUSDT", st.L_maCross_avg_t),
        ("ADAUSDT", st.L_maCross_avg_t),
        ("LINKUSDT", st.L_maCross_avg_t),
        ("ETHUSDT", st.L_maCross_dema_t),
        ("LINKUSDT", st.L_maCross_dema_t),
        ("BTCUSDT", st.L_maCross_ema_t),
        ("ADAUSDT", st.L_maCross_ema_t),
        ("ETHUSDT", st.L_maCross_ema_t),
        ("XLMUSDT", st.L_maCross_ema_t),
        ("ADAUSDT", st.L_maCross_kama_t),
        ("BTCUSDT", st.L_maCross_kama_t),
        ("LINKUSDT", st.L_maCross_kama_t),
        ("XLMUSDT", st.L_maCross_kama_t),
        ("ETHUSDT", st.L_maCross_mama_t),
        ("BTCUSDT", st.L_maCross_mama_t),
        ("BTCUSDT", st.L_maCross_med_t),
        ("ADAUSDT", st.L_maCross_med_t),
        ("LINKUSDT", st.L_maCross_med_t),
        ("BTCUSDT", st.L_maCross_midprice_t),
        ("LINKUSDT", st.L_maCross_midprice_t),
        ("LTCUSDT", st.L_maCross_midprice_t),
        ("ETHUSDT", st.L_maCross_midprice_t),
        ("BTCUSDT", st.L_maCross_trima_t),
        ("XLMUSDT", st.L_maCross_trima_t),
        ("BTCUSDT", st.L_maCross_typical_t),
        ("ETHUSDT", st.L_maCross_typical_t),
        ("ADAUSDT", st.L_maCross_typical_t),
        ("LINKUSDT", st.L_maCross_typical_t),
        ("BTCUSDT", st.L_maCross_wclprice_t),
        ("ETHUSDT", st.L_maCross_wclprice_t),
        ("ADAUSDT", st.L_maCross_wclprice_t),
        ("LINKUSDT", st.L_maCross_wclprice_t),
        ("LINKUSDT", st.L_maCross_wma_t),
        ("BTCUSDT", st.L_maCross_wma_t),
        ("XLMUSDT", st.L_maCross_wma_t),
        ("XRPUSDT", st.L_maCross_wma_t),
        ("ETHUSDT", st.L_maCross_wma_t),
        ("BTCUSDT", st.M_rsi_fromInner_t),
        ("BNBUSDT", st.M_rsi_fromOuter_t),
        ("LINKUSDT", st.M_rsi_linearReg__t),
        ("XLMUSDT", st.M_rsi_linearReg__t),
        ("LINKUSDT", st.M_rsi_linearReg_avg_t),
        ("XLMUSDT", st.M_rsi_linearReg_avg_t),
        ("LINKUSDT", st.M_rsi_linearReg_med_t),
        ("XLMUSDT", st.M_rsi_linearReg_med_t),
        ("LINKUSDT", st.M_rsi_linearReg_typical_t),
        ("XLMUSDT", st.M_rsi_linearReg_typical_t),
        ("LINKUSDT", st.M_rsi_linearReg_wclprice_t),
        ("XLMUSDT", st.M_rsi_linearReg_wclprice_t),
        ("LINKUSDT", st.M_rsi_maBo_t),
        ("ETHUSDT", st.M_rsi_maBo_t),
        ("XRPUSDT", st.M_rsi_maBo_t),
        ("XLMUSDT", st.M_rsi_maBo_t),
        ("BTCUSDT", st.M_rsi_maBo_t),
        ("XLMUSDT", st.M_rsi_trix_t),
        ("ETHUSDT", st.M_rsi_tsf_t),
        ("BTCUSDT", st.M_rsi_tsf_t),
        ("ETHUSDT", st.N_sar_htTrend_t),
        ("BTCUSDT", st.N_sar_typical_t),
        ("BTCUSDT", st.N_sar_wclprice_t),
        ("ETHUSDT", st.O_spike__t),
        ("LTCUSDT", st.O_spike__t),
        ("LTCUSDT", st.O_spike_atr_t),
        ("LTCUSDT", st.O_spike_max_t),
        ("XRPUSDT", st.O_spike_max_t),
        ("ETHUSDT", st.O_spike_max_t),
        ("ETHUSDT", st.O_spike_maxAtr__t),
        ("ETHUSDT", st.O_spike_maxAtr_avg_t),
        ("ADAUSDT", st.O_spike_maxAtr_avg_t),
        ("BTCUSDT", st.O_spike_maxAtr_avg_t),
        ("XRPUSDT", st.O_spike_maxAtr_avg_t),
        ("ETHUSDT", st.O_spike_maxAtr_med_t),
        ("XLMUSDT", st.O_spike_maxAtr_med_t),
        ("BTCUSDT", st.O_spike_maxAtr_med_t),
        ("ADAUSDT", st.O_spike_maxAtr_med_t),
        ("ETHUSDT", st.O_spike_maxAtr_typical_t),
        ("ADAUSDT", st.O_spike_maxAtr_typical_t),
        ("LINKUSDT", st.O_spike_maxAtr_typical_t),
        ("LTCUSDT", st.O_spike_maxAtr_typical_t),
        ("BTCUSDT", st.O_spike_maxAtr_typical_t),
        ("ETHUSDT", st.O_spike_maxAtr_wclprice_t),
        ("BTCUSDT", st.O_spike_maxAtr_wclprice_t),
        ("ADAUSDT", st.O_spike_maxAtr_wclprice_t),
        ("LINKUSDT", st.O_spike_maxAtr_wclprice_t),
        ("ETHUSDT", st.O_spike_med_t),
        ("ETHUSDT", st.O_spike_typical_t),
        ("LTCUSDT", st.O_spike_typical_t),
        ("ETHUSDT", st.O_spike_wclprice_t),
        ("LTCUSDT", st.O_spike_wclprice_t),
        ("BTCUSDT", st.P_stoch_fromInner_t),
        ("LINKUSDT", st.P_stoch_fromInner_t),
        ("ADAUSDT", st.P_stoch_fromInner_t),
        ("ETHUSDT", st.P_stoch_fromInner_t),
        ("XLMUSDT", st.P_stoch_fromInner_t),
        ("BTCUSDT", st.P_stoch_fromOuter_t),
        ("ETHUSDT", st.P_stoch_fromOuter_t),
        ("ADAUSDT", st.P_stoch_fromOuter_t),
        ("XRPUSDT", st.P_stoch_linearReg_t),
        ("ETHUSDT", st.P_stoch_maBo_t),
        ("LINKUSDT", st.P_stoch_trix_t),
        ("XRPUSDT", st.Q_stochrsi_fromInner_t),
        ("BTCUSDT", st.Q_stochrsi_fromInner_t),
        ("ETHUSDT", st.Q_stochrsi_fromInner_t),
        ("ADAUSDT", st.Q_stochrsi_fromInner_t),
        ("XLMUSDT", st.Q_stochrsi_fromInner_t),
        ("BNBUSDT", st.Q_stochrsi_fromInner_t),
        ("ETHUSDT", st.Q_stochrsi_fromOuter_t),
        ("BTCUSDT", st.Q_stochrsi_fromOuter_t),
        ("XLMUSDT", st.Q_stochrsi_linearReg_t),
        ("ADAUSDT", st.Q_stochrsi_linearReg_t),
        ("BTCUSDT", st.Q_stochrsi_maBo_t),
        ("BNBUSDT", st.Q_stochrsi_trix_t),
        ("XLMUSDT", st.Q_stochrsi_trix_t),
        ("BTCUSDT", st.R_tailbarClose__t),
        ("ADAUSDT", st.R_tailbarClose__t),
        ("ADAUSDT", st.R_tailbarClose_trix_t),
        ("ETHUSDT", st.R_tailbarClose_trix_t),
        ("ETHUSDT", st.S_trend__t),
        ("BTCUSDT", st.S_trend__t),
        ("XRPUSDT", st.S_trend__t),
        ("ADAUSDT", st.S_trend__t),
        ("ETHUSDT", st.S_trend_avg_t),
        ("BTCUSDT", st.S_trend_avg_t),
        ("XRPUSDT", st.S_trend_avg_t),
        ("ADAUSDT", st.S_trend_avg_t),
        ("ETHUSDT", st.S_trend_med_t),
        ("ADAUSDT", st.S_trend_med_t),
        ("BTCUSDT", st.S_trend_med_t),
        ("XRPUSDT", st.S_trend_med_t),
        ("LINKUSDT", st.S_trend_med_t),
        ("ETHUSDT", st.S_trend_typ_t),
        ("BTCUSDT", st.S_trend_typ_t),
        ("XRPUSDT", st.S_trend_typ_t),
        ("ADAUSDT", st.S_trend_typ_t),
        ("ETHUSDT", st.S_trend_wclprice_t),
        ("BTCUSDT", st.S_trend_wclprice_t),
        ("XRPUSDT", st.S_trend_wclprice_t),
        ("ADAUSDT", st.S_trend_wclprice_t),
        ("ETHUSDT", st.S_trendChange_bo_t),
        ("BTCUSDT", st.S_trendChange_bo_t),
        ("LINKUSDT", st.S_trendChange_bo_t),
        ("LTCUSDT", st.S_trendChange_linearReg_t),
        ("LINKUSDT", st.S_trendChange_linearReg_t),
        ("BTCUSDT", st.S_trendChange_linearReg_t),
        ("XLMUSDT", st.S_trendChange_linearReg_t),
        ("ETHUSDT", st.S_trendChange_maBo_t),
        ("BTCUSDT", st.S_trendChange_maBo_t),
        ("BTCUSDT", st.S_trendChange_trix_t),
        ("ADAUSDT", st.S_trendRolling__t),
        ("XRPUSDT", st.S_trendRolling__t),
        ("ETHUSDT", st.S_trendRolling__t),
        ("LINKUSDT", st.S_trendRolling__t),
        ("ETHUSDT", st.S_trendRolling_avg_t),
        ("XRPUSDT", st.S_trendRolling_avg_t),
        ("BNBUSDT", st.S_trendRolling_avg_t),
        ("ADAUSDT", st.S_trendRolling_med_t),
        ("ETHUSDT", st.S_trendRolling_med_t),
        ("XRPUSDT", st.S_trendRolling_med_t),
        ("ADAUSDT", st.S_trendRolling_typical_t),
        ("ETHUSDT", st.S_trendRolling_typical_t),
        ("XRPUSDT", st.S_trendRolling_typical_t),
        ("BNBUSDT", st.S_trendRolling_typical_t),
        ("ADAUSDT", st.S_trendRolling_wclprice_t),
        ("XRPUSDT", st.S_trendRolling_wclprice_t),
        ("ETHUSDT", st.S_trendRolling_wclprice_t),
        ("BNBUSDT", st.S_trendRolling_wclprice_t),
        ("ETHUSDT", st.T_trix__t),
        ("BTCUSDT", st.T_trix__t),
        ("BTCUSDT", st.T_trix_avg_t),
        ("ETHUSDT", st.T_trix_avg_t),
        ("XLMUSDT", st.T_trix_maBo_t),
        ("BTCUSDT", st.T_trix_med_t),
        ("ETHUSDT", st.T_trix_med_t),
        ("XLMUSDT", st.T_trix_tsf_t),
        ("BTCUSDT", st.T_trix_typical_t),
        ("ETHUSDT", st.T_trix_typical_t),
        ("XLMUSDT", st.T_trix_typical_t),
        ("ETHUSDT", st.T_trix_wclprice_t),
        ("BTCUSDT", st.T_trix_wclprice_t),
        ("XLMUSDT", st.T_trix_wclprice_t),
        ("ETHUSDT", st.U_tsf_avg_t),
        ("ETHUSDT", st.U_tsf_linearReg_t),
        ("BTCUSDT", st.U_tsf_linearReg_t),
        ("XRPUSDT", st.U_tsf_linearReg_t),
        ("LINKUSDT", st.U_tsf_linearReg_t),
        ("ETHUSDT", st.U_tsf_maBo_t),
        ("LINKUSDT", st.U_tsf_maBo_t),
        ("XLMUSDT", st.U_tsf_maBo_t),
        ("ETHUSDT", st.U_tsf_med_t),
        ("ETHUSDT", st.U_tsf_trix_t),
        ("XRPUSDT", st.U_tsf_trix_t),
        ("XLMUSDT", st.U_tsf_trix_t),
        ("ETHUSDT", st.U_tsf_typical_t),
        ("ETHUSDT", st.U_tsf_wclprice_t),
        ("BTCUSDT", st.V_ultimate_fromInner_t),
        ("ETHUSDT", st.V_ultimate_htTrend_fromInner_t),
        ("BTCUSDT", st.V_ultimate_htTrend_fromInner_t),
        ("LTCUSDT", st.V_ultimate_htTrend_fromInner_t),
        ("XLMUSDT", st.V_ultimate_trix_t),
        ("BTCUSDT", st.W_willR_fromOuter_t),
        ("ETHUSDT", st.W_willR_fromOuter_t),
        ("ETHUSDT", st.W_willR_htTrend_fromOuter_t),
        ("BTCUSDT", st.W_willR_htTrend_fromOuter_t),
        ("XRPUSDT", st.W_willR_linearReg_t),
        ("ETHUSDT", st.W_willR_maBo_t),
        ("LINKUSDT", st.W_willR_trix_t),
        ("XLMUSDT", st.Z_3InsideUpDown),
        ("XRPUSDT", st.Z_3LineStrike),
        ("BNBUSDT", st.Z_3whiteSoldiers),
        ("ADAUSDT", st.Z_doji),
        ("ETHUSDT", st.Z_doji),
        ("XRPUSDT", st.Z_doji),
        ("LINKUSDT", st.Z_doji),
        ("BTCUSDT", st.Z_doji),
        ("BTCUSDT", st.Z_dragonFly),
        ("LTCUSDT", st.Z_hammer),
        ("BTCUSDT", st.Z_haramiCross),
        ("EOSUSDT", st.Z_hikkakeMod),
        ("ADAUSDT", st.Z_longDoji),
        ("ETHUSDT", st.Z_longDoji),
        ("XRPUSDT", st.Z_longDoji),
        ("LINKUSDT", st.Z_longDoji),
        ("BTCUSDT", st.Z_longDoji),
        ("ADAUSDT", st.Z_richshawMan),
        ("ETHUSDT", st.Z_richshawMan),
        ("LINKUSDT", st.Z_richshawMan),
        ("XRPUSDT", st.Z_richshawMan),
        ("BTCUSDT", st.Z_richshawMan),
    ]

    if combinations is not None:
        if len(combinations) == 0:
            combinations = None
    return routine, symbols, strategies_list, combinations, use_parallel_compute, dates


def get_routine_dates(routine: str | None) -> tuple[datetime, datetime]:
    """
    Gets the start and end dates for a specific routine phase.

    Parameters:
    routine (Optional[str]): The routine phase for which dates are required.

    Returns:
    Tuple[datetime, datetime]: The start and end dates of the specified routine phase.

    Raises:
    ValueError: If the routine is invalid.
    """
    # reference_date == oos_phase_end
    reference_date: datetime = snap_date(datetime(2025, 1, 1))
    days_per_year: float = 365.2425

    # oos_phase: 2 years lookback
    oos_phase_end: datetime = reference_date
    oos_phase_start: datetime = snap_date(oos_phase_end - timedelta(days=days_per_year * 2.0))

    # validation_phase: 2 years lookback
    validation_phase_end: datetime = oos_phase_start
    validation_phase_start: datetime = snap_date(validation_phase_end - timedelta(days=days_per_year * 2.0))

    # initial_selection: 1 year lookback
    initial_selection_end: datetime = validation_phase_start
    initial_selection_start: datetime = snap_date(initial_selection_end - timedelta(days=days_per_year * 1.0))

    # parameter_range: 1 year lookback
    parameter_range_end: datetime = initial_selection_start
    parameter_range_start: datetime = snap_date(parameter_range_end - timedelta(days=days_per_year * 1.0))

    match routine:
        case 'oos_phase':
            return oos_phase_start, oos_phase_end
        case 'validation_phase':
            return validation_phase_start, validation_phase_end
        case 'validation_phase_ave_psr':
            return validation_phase_start, validation_phase_end
        case 'initial_selection':
            return initial_selection_start, initial_selection_end
        case 'initial_selection_ave_psr':
            return initial_selection_start, initial_selection_end
        case 'parameter_count':
            return initial_selection_start, initial_selection_end
        case 'parameter_range':
            return parameter_range_start, parameter_range_end
        case 'custom':
            return snap_date(validation_phase_start - timedelta(days=days_per_year * 2.0)), validation_phase_start
        case _:
            raise ValueError(f'Invalid routine {routine}')
