from strategies_package.A_aroon_fromInner_ct import *
from strategies_package.A_aroon_fromInner_t import *
from strategies_package.A_aroon_fromOuter_ct import *
from strategies_package.A_aroon_fromOuter_t import *
from strategies_package.A_aroon_htTrend_fromInner_ct import *
from strategies_package.A_aroon_htTrend_fromInner_t import *
from strategies_package.A_aroon_htTrend_fromOuter_ct import *
from strategies_package.A_aroon_htTrend_fromOuter_t import *
from strategies_package.A_aroon_linearReg_ct import *
from strategies_package.A_aroon_linearReg_t import *
from strategies_package.A_aroon_maBo_ct import *
from strategies_package.A_aroon_maBo_t import *
from strategies_package.A_aroon_trix_ct import *
from strategies_package.A_aroon_trix_t import *
from strategies_package.A_aroon_tsf_ct import *
from strategies_package.A_aroon_tsf_t import *
from strategies_package.B_adosc__ct import *
from strategies_package.B_adosc__t import *
from strategies_package.B_adosc_linearReg_ct import *
from strategies_package.B_adosc_linearReg_t import *
from strategies_package.B_adosc_maBo_ct import *
from strategies_package.B_adosc_maBo_t import *
from strategies_package.B_adosc_tsf_ct import *
from strategies_package.B_adosc_tsf_t import *
from strategies_package.B_mfi_fromInner_ct import *
from strategies_package.B_mfi_fromInner_t import *
from strategies_package.B_mfi_fromOuter_ct import *
from strategies_package.B_mfi_fromOuter_t import *
from strategies_package.B_mfi_linearReg_ct import *
from strategies_package.B_mfi_linearReg_t import *
from strategies_package.B_mfi_trix_ct import *
from strategies_package.B_mfi_trix_t import *
from strategies_package.B_mfi_tsf_ct import *
from strategies_package.B_mfi_tsf_t import *
from strategies_package.B_obv_breakout_ct import *
from strategies_package.B_obv_breakout_t import *
from strategies_package.B_obv_linearReg_ct import *
from strategies_package.B_obv_linearReg_t import *
from strategies_package.B_obv_maBo_ct import *
from strategies_package.B_obv_maBo_t import *
from strategies_package.B_obv_tsf_ct import *
from strategies_package.B_obv_tsf_t import *
from strategies_package.C_bop__ct import *
from strategies_package.C_bop__t import *
from strategies_package.C_bop_count_ct import *
from strategies_package.C_bop_count_t import *
from strategies_package.C_bop_linearReg_ct import *
from strategies_package.C_bop_linearReg_t import *
from strategies_package.C_bop_maCross_ct import *
from strategies_package.C_bop_maCross_t import *
from strategies_package.C_bop_posMinusNeg_ct import *
from strategies_package.C_bop_posMinusNeg_t import *
from strategies_package.C_bop_trix_ct import *
from strategies_package.C_bop_trix_t import *
from strategies_package.C_bop_tsf_ct import *
from strategies_package.C_bop_tsf_t import *
from strategies_package.D_adx__ct import *
from strategies_package.D_adx__t import *
from strategies_package.D_adx_linearReg_ct import *
from strategies_package.D_adx_linearReg_t import *
from strategies_package.D_adx_ma_ct import *
from strategies_package.D_adx_ma_t import *
from strategies_package.D_adx_trix_ct import *
from strategies_package.D_adx_trix_t import *
from strategies_package.D_adx_tsf_ct import *
from strategies_package.D_adx_tsf_t import *
from strategies_package.D_bollingerBreakout_fromInner_ct import *
from strategies_package.D_bollingerBreakout_fromInner_t import *
from strategies_package.D_bollingerBreakout_fromOuter_ct import *
from strategies_package.D_bollingerBreakout_fromOuter_t import *
from strategies_package.D_breakoutHighLow_ct import *
from strategies_package.D_breakoutHighLow_t import *
from strategies_package.D_breakout__ct import *
from strategies_package.D_breakout__t import *
from strategies_package.D_breakout_avg_ct import *
from strategies_package.D_breakout_avg_t import *
from strategies_package.D_breakout_med_ct import *
from strategies_package.D_breakout_med_t import *
from strategies_package.D_breakout_typical_ct import *
from strategies_package.D_breakout_typical_t import *
from strategies_package.D_breakout_wclprice_ct import *
from strategies_package.D_breakout_wclprice_t import *
from strategies_package.D_dynamic_ct import *
from strategies_package.D_dynamic_t import *
from strategies_package.D_htTrend_breakout_ct import *
from strategies_package.D_htTrend_breakout_t import *
from strategies_package.D_keltnerBreakout_fromInner_ct import *
from strategies_package.D_keltnerBreakout_fromInner_t import *
from strategies_package.D_keltnerBreakout_fromOuter_ct import *
from strategies_package.D_keltnerBreakout_fromOuter_t import *
from strategies_package.D_stdev_ma_ct import *
from strategies_package.D_stdev_ma_t import *
from strategies_package.D_tsf_breakout_ct import *
from strategies_package.D_tsf_breakout_t import *
from strategies_package.D_turtle_ct import *
from strategies_package.D_turtle_t import *
from strategies_package.E_cci_fromInner_ct import *
from strategies_package.E_cci_fromInner_t import *
from strategies_package.E_cci_fromOuter_ct import *
from strategies_package.E_cci_fromOuter_t import *
from strategies_package.E_cci_htTrend_fromInner_ct import *
from strategies_package.E_cci_htTrend_fromInner_t import *
from strategies_package.E_cci_htTrend_fromOuter_ct import *
from strategies_package.E_cci_htTrend_fromOuter_t import *
from strategies_package.E_cci_linearReg_ct import *
from strategies_package.E_cci_linearReg_t import *
from strategies_package.E_cci_maBo_ct import *
from strategies_package.E_cci_maBo_t import *
from strategies_package.E_cci_tsf_ct import *
from strategies_package.E_cci_tsf_t import *
from strategies_package.F_cmo_fromInner_ct import *
from strategies_package.F_cmo_fromInner_t import *
from strategies_package.F_cmo_fromOuter_ct import *
from strategies_package.F_cmo_fromOuter_t import *
from strategies_package.F_cmo_htTrend_fromInner_ct import *
from strategies_package.F_cmo_htTrend_fromInner_t import *
from strategies_package.F_cmo_htTrend_fromOuter_ct import *
from strategies_package.F_cmo_htTrend_fromOuter_t import *
from strategies_package.F_cmo_linearReg_ct import *
from strategies_package.F_cmo_linearReg_t import *
from strategies_package.F_cmo_maBo__ct import *
from strategies_package.F_cmo_maBo__t import *
from strategies_package.F_cmo_maBo_avg_ct import *
from strategies_package.F_cmo_maBo_avg_t import *
from strategies_package.F_cmo_maBo_med_ct import *
from strategies_package.F_cmo_maBo_med_t import *
from strategies_package.F_cmo_maBo_typical_ct import *
from strategies_package.F_cmo_maBo_typical_t import *
from strategies_package.F_cmo_maBo_wclprice_ct import *
from strategies_package.F_cmo_maBo_wclprice_t import *
from strategies_package.F_cmo_tsf_ct import *
from strategies_package.F_cmo_tsf_t import *
from strategies_package.G_adx_dm_ct import *
from strategies_package.G_adx_dm_t import *
from strategies_package.G_adx_linearReg_dm_ct import *
from strategies_package.G_adx_linearReg_dm_t import *
from strategies_package.G_adx_trix_dm_ct import *
from strategies_package.G_adx_trix_dm_t import *
from strategies_package.G_dm__ct import *
from strategies_package.G_dm__t import *
from strategies_package.G_dm_htTrend_ct import *
from strategies_package.G_dm_htTrend_t import *
from strategies_package.G_dm_linearReg_ct import *
from strategies_package.G_dm_linearReg_t import *
from strategies_package.G_dm_trix_ct import *
from strategies_package.G_dm_trix_t import *
from strategies_package.G_dm_tsf_ct import *
from strategies_package.G_dm_tsf_t import *
from strategies_package.H_hilbertSine__ct import *
from strategies_package.H_hilbertSine__t import *
from strategies_package.H_hilbertSine_avg_ct import *
from strategies_package.H_hilbertSine_avg_t import *
from strategies_package.H_hilbertSine_med_ct import *
from strategies_package.H_hilbertSine_med_t import *
from strategies_package.H_hilbertSine_typical_ct import *
from strategies_package.H_hilbertSine_typical_t import *
from strategies_package.H_hilbertSine_wclprice_ct import *
from strategies_package.H_hilbertSine_wclprice_t import *
from strategies_package.H_hilbertTrendMode_ct import *
from strategies_package.H_hilbertTrendMode_t import *
from strategies_package.H_hilbertTrend__ct import *
from strategies_package.H_hilbertTrend__t import *
from strategies_package.H_hilbertTrend_avg_ct import *
from strategies_package.H_hilbertTrend_avg_t import *
from strategies_package.H_hilbertTrend_linearReg_ct import *
from strategies_package.H_hilbertTrend_linearReg_t import *
from strategies_package.H_hilbertTrend_med_ct import *
from strategies_package.H_hilbertTrend_med_t import *
from strategies_package.H_hilbertTrend_trix_ct import *
from strategies_package.H_hilbertTrend_trix_t import *
from strategies_package.H_hilbertTrend_tsf_ct import *
from strategies_package.H_hilbertTrend_tsf_t import *
from strategies_package.H_hilbertTrend_typical_ct import *
from strategies_package.H_hilbertTrend_typical_t import *
from strategies_package.H_hilbertTrend_wclprice_ct import *
from strategies_package.H_hilbertTrend_wclprice_t import *
from strategies_package.I_maBoDiff_breakout_ct import *
from strategies_package.I_maBoDiff_breakout_t import *
from strategies_package.I_maBoDiff_linearReg_ct import *
from strategies_package.I_maBoDiff_linearReg_t import *
from strategies_package.I_maBoDiff_tsf_ct import *
from strategies_package.I_maBoDiff_tsf_t import *
from strategies_package.I_maBo__ct import *
from strategies_package.I_maBo__t import *
from strategies_package.I_maBo_avg_ct import *
from strategies_package.I_maBo_avg_t import *
from strategies_package.I_maBo_dema_ct import *
from strategies_package.I_maBo_dema_t import *
from strategies_package.I_maBo_ema_ct import *
from strategies_package.I_maBo_ema_t import *
from strategies_package.I_maBo_kama_ct import *
from strategies_package.I_maBo_kama_t import *
from strategies_package.I_maBo_mama_ct import *
from strategies_package.I_maBo_mama_t import *
from strategies_package.I_maBo_med_ct import *
from strategies_package.I_maBo_med_t import *
from strategies_package.I_maBo_midprice_ct import *
from strategies_package.I_maBo_midprice_t import *
from strategies_package.I_maBo_tema_ct import *
from strategies_package.I_maBo_tema_t import *
from strategies_package.I_maBo_trima_ct import *
from strategies_package.I_maBo_trima_t import *
from strategies_package.I_maBo_typical_ct import *
from strategies_package.I_maBo_typical_t import *
from strategies_package.I_maBo_wclprice_ct import *
from strategies_package.I_maBo_wclprice_t import *
from strategies_package.I_maBo_wma_ct import *
from strategies_package.I_maBo_wma_t import *
from strategies_package.J_linearReg__ct import *
from strategies_package.J_linearReg__t import *
from strategies_package.J_linearReg_avg_ct import *
from strategies_package.J_linearReg_avg_t import *
from strategies_package.J_linearReg_linearReg_ct import *
from strategies_package.J_linearReg_linearReg_t import *
from strategies_package.J_linearReg_maBo_ct import *
from strategies_package.J_linearReg_maBo_t import *
from strategies_package.J_linearReg_med_ct import *
from strategies_package.J_linearReg_med_t import *
from strategies_package.J_linearReg_trix_ct import *
from strategies_package.J_linearReg_trix_t import *
from strategies_package.J_linearReg_tsf_ct import *
from strategies_package.J_linearReg_tsf_t import *
from strategies_package.J_linearReg_typical_ct import *
from strategies_package.J_linearReg_typical_t import *
from strategies_package.J_linearReg_wclprice_ct import *
from strategies_package.J_linearReg_wclprice_t import *
from strategies_package.K_macd__ct import *
from strategies_package.K_macd__t import *
from strategies_package.K_macd_avg_ct import *
from strategies_package.K_macd_avg_t import *
from strategies_package.K_macd_breakout_ct import *
from strategies_package.K_macd_breakout_t import *
from strategies_package.K_macd_linearRegSignal_ct import *
from strategies_package.K_macd_linearRegSignal_t import *
from strategies_package.K_macd_linearReg_ct import *
from strategies_package.K_macd_linearReg_t import *
from strategies_package.K_macd_med_ct import *
from strategies_package.K_macd_med_t import *
from strategies_package.K_macd_tsf_ct import *
from strategies_package.K_macd_tsf_t import *
from strategies_package.K_macd_typical_ct import *
from strategies_package.K_macd_typical_t import *
from strategies_package.K_macd_wclprice_ct import *
from strategies_package.K_macd_wclprice_t import *
from strategies_package.L_maCross__ct import *
from strategies_package.L_maCross__t import *
from strategies_package.L_maCross_avg_ct import *
from strategies_package.L_maCross_avg_t import *
from strategies_package.L_maCross_dema_ct import *
from strategies_package.L_maCross_dema_t import *
from strategies_package.L_maCross_ema_ct import *
from strategies_package.L_maCross_ema_t import *
from strategies_package.L_maCross_kama_ct import *
from strategies_package.L_maCross_kama_t import *
from strategies_package.L_maCross_mama_ct import *
from strategies_package.L_maCross_mama_t import *
from strategies_package.L_maCross_med_ct import *
from strategies_package.L_maCross_med_t import *
from strategies_package.L_maCross_midprice_ct import *
from strategies_package.L_maCross_midprice_t import *
from strategies_package.L_maCross_tema_ct import *
from strategies_package.L_maCross_tema_t import *
from strategies_package.L_maCross_trima_ct import *
from strategies_package.L_maCross_trima_t import *
from strategies_package.L_maCross_typical_ct import *
from strategies_package.L_maCross_typical_t import *
from strategies_package.L_maCross_wclprice_ct import *
from strategies_package.L_maCross_wclprice_t import *
from strategies_package.L_maCross_wma_ct import *
from strategies_package.L_maCross_wma_t import *
from strategies_package.M_rsi_fromInner_ct import *
from strategies_package.M_rsi_fromInner_t import *
from strategies_package.M_rsi_fromOuter_ct import *
from strategies_package.M_rsi_fromOuter_t import *
from strategies_package.M_rsi_linearReg__ct import *
from strategies_package.M_rsi_linearReg__t import *
from strategies_package.M_rsi_linearReg_avg_ct import *
from strategies_package.M_rsi_linearReg_avg_t import *
from strategies_package.M_rsi_linearReg_med_ct import *
from strategies_package.M_rsi_linearReg_med_t import *
from strategies_package.M_rsi_linearReg_typical_ct import *
from strategies_package.M_rsi_linearReg_typical_t import *
from strategies_package.M_rsi_linearReg_wclprice_ct import *
from strategies_package.M_rsi_linearReg_wclprice_t import *
from strategies_package.M_rsi_maBo_ct import *
from strategies_package.M_rsi_maBo_t import *
from strategies_package.M_rsi_trix_ct import *
from strategies_package.M_rsi_trix_t import *
from strategies_package.M_rsi_tsf_ct import *
from strategies_package.M_rsi_tsf_t import *
from strategies_package.N_sar__ct import *
from strategies_package.N_sar__t import *
from strategies_package.N_sar_avg_ct import *
from strategies_package.N_sar_avg_t import *
from strategies_package.N_sar_close_ct import *
from strategies_package.N_sar_close_t import *
from strategies_package.N_sar_htTrend_ct import *
from strategies_package.N_sar_htTrend_t import *
from strategies_package.N_sar_med_ct import *
from strategies_package.N_sar_med_t import *
from strategies_package.N_sar_typical_ct import *
from strategies_package.N_sar_typical_t import *
from strategies_package.N_sar_wclprice_ct import *
from strategies_package.N_sar_wclprice_t import *
from strategies_package.O_spike__ct import *
from strategies_package.O_spike__t import *
from strategies_package.O_spike_atr_ct import *
from strategies_package.O_spike_atr_t import *
from strategies_package.O_spike_avg_ct import *
from strategies_package.O_spike_avg_t import *
from strategies_package.O_spike_maxAtr_avg_ct import *
from strategies_package.O_spike_maxAtr_avg_t import *
from strategies_package.O_spike_maxAtr_ct import *
from strategies_package.O_spike_maxAtr_med_ct import *
from strategies_package.O_spike_maxAtr_med_t import *
from strategies_package.O_spike_maxAtr_t import *
from strategies_package.O_spike_maxAtr_typical_ct import *
from strategies_package.O_spike_maxAtr_typical_t import *
from strategies_package.O_spike_maxAtr_wclprice_ct import *
from strategies_package.O_spike_maxAtr_wclprice_t import *
from strategies_package.O_spike_maxTr_ct import *
from strategies_package.O_spike_maxTr_t import *
from strategies_package.O_spike_max_ct import *
from strategies_package.O_spike_max_t import *
from strategies_package.O_spike_med_ct import *
from strategies_package.O_spike_med_t import *
from strategies_package.O_spike_typical_ct import *
from strategies_package.O_spike_typical_t import *
from strategies_package.O_spike_wclprice_ct import *
from strategies_package.O_spike_wclprice_t import *
from strategies_package.P_stoch__ct import *
from strategies_package.P_stoch__t import *
from strategies_package.P_stoch_fromInner_ct import *
from strategies_package.P_stoch_fromInner_t import *
from strategies_package.P_stoch_fromOuter_ct import *
from strategies_package.P_stoch_fromOuter_t import *
from strategies_package.P_stoch_linearReg_ct import *
from strategies_package.P_stoch_linearReg_t import *
from strategies_package.P_stoch_maBo_ct import *
from strategies_package.P_stoch_maBo_t import *
from strategies_package.P_stoch_thresh_ct import *
from strategies_package.P_stoch_thresh_t import *
from strategies_package.P_stoch_trix_ct import *
from strategies_package.P_stoch_trix_t import *
from strategies_package.P_stoch_tsf_ct import *
from strategies_package.P_stoch_tsf_t import *
from strategies_package.Q_stochrsi__ct import *
from strategies_package.Q_stochrsi__t import *
from strategies_package.Q_stochrsi_fromInner_ct import *
from strategies_package.Q_stochrsi_fromInner_t import *
from strategies_package.Q_stochrsi_fromOuter_ct import *
from strategies_package.Q_stochrsi_fromOuter_t import *
from strategies_package.Q_stochrsi_linearReg_ct import *
from strategies_package.Q_stochrsi_linearReg_t import *
from strategies_package.Q_stochrsi_maBo_ct import *
from strategies_package.Q_stochrsi_maBo_t import *
from strategies_package.Q_stochrsi_thresh_ct import *
from strategies_package.Q_stochrsi_thresh_t import *
from strategies_package.Q_stochrsi_trix_ct import *
from strategies_package.Q_stochrsi_trix_t import *
from strategies_package.Q_stochrsi_tsf_ct import *
from strategies_package.Q_stochrsi_tsf_t import *
from strategies_package.R_tailbarClose__ct import *
from strategies_package.R_tailbarClose__t import *
from strategies_package.R_tailbarClose_linearReg_ct import *
from strategies_package.R_tailbarClose_linearReg_t import *
from strategies_package.R_tailbarClose_maBo_ct import *
from strategies_package.R_tailbarClose_maBo_t import *
from strategies_package.R_tailbarClose_trix_ct import *
from strategies_package.R_tailbarClose_trix_t import *
from strategies_package.R_tailbarClose_tsf_ct import *
from strategies_package.R_tailbarClose_tsf_t import *
from strategies_package.R_tailbar__ct import *
from strategies_package.R_tailbar__t import *
from strategies_package.R_tailbar_linearReg_ct import *
from strategies_package.R_tailbar_linearReg_t import *
from strategies_package.R_tailbar_maBo_ct import *
from strategies_package.R_tailbar_maBo_t import *
from strategies_package.R_tailbar_trix_ct import *
from strategies_package.R_tailbar_trix_t import *
from strategies_package.R_tailbar_tsf_ct import *
from strategies_package.R_tailbar_tsf_t import *
from strategies_package.S_trendChange_bo_ct import *
from strategies_package.S_trendChange_bo_t import *
from strategies_package.S_trendChange_linearReg_ct import *
from strategies_package.S_trendChange_linearReg_t import *
from strategies_package.S_trendChange_maBo_ct import *
from strategies_package.S_trendChange_maBo_t import *
from strategies_package.S_trendChange_trix_ct import *
from strategies_package.S_trendChange_trix_t import *
from strategies_package.S_trendChange_tsf_ct import *
from strategies_package.S_trendChange_tsf_t import *
from strategies_package.S_trendRolling__ct import *
from strategies_package.S_trendRolling__t import *
from strategies_package.S_trendRolling_avg_ct import *
from strategies_package.S_trendRolling_avg_t import *
from strategies_package.S_trendRolling_linearReg_ct import *
from strategies_package.S_trendRolling_linearReg_t import *
from strategies_package.S_trendRolling_maBo_ct import *
from strategies_package.S_trendRolling_maBo_t import *
from strategies_package.S_trendRolling_med_ct import *
from strategies_package.S_trendRolling_med_t import *
from strategies_package.S_trendRolling_trix_ct import *
from strategies_package.S_trendRolling_trix_t import *
from strategies_package.S_trendRolling_tsf_ct import *
from strategies_package.S_trendRolling_tsf_t import *
from strategies_package.S_trendRolling_typical_ct import *
from strategies_package.S_trendRolling_typical_t import *
from strategies_package.S_trendRolling_wclprice_ct import *
from strategies_package.S_trendRolling_wclprice_t import *
from strategies_package.S_trend__ct import *
from strategies_package.S_trend__t import *
from strategies_package.S_trend_avg_ct import *
from strategies_package.S_trend_avg_t import *
from strategies_package.S_trend_med_ct import *
from strategies_package.S_trend_med_t import *
from strategies_package.S_trend_typ_ct import *
from strategies_package.S_trend_typ_t import *
from strategies_package.S_trend_wclprice_ct import *
from strategies_package.S_trend_wclprice_t import *
from strategies_package.T_trix__ct import *
from strategies_package.T_trix__t import *
from strategies_package.T_trix_avg_ct import *
from strategies_package.T_trix_avg_t import *
from strategies_package.T_trix_bo_ct import *
from strategies_package.T_trix_bo_t import *
from strategies_package.T_trix_linearReg_ct import *
from strategies_package.T_trix_linearReg_t import *
from strategies_package.T_trix_maBo_ct import *
from strategies_package.T_trix_maBo_t import *
from strategies_package.T_trix_med_ct import *
from strategies_package.T_trix_med_t import *
from strategies_package.T_trix_tsf_ct import *
from strategies_package.T_trix_tsf_t import *
from strategies_package.T_trix_typical_ct import *
from strategies_package.T_trix_typical_t import *
from strategies_package.T_trix_wclprice_ct import *
from strategies_package.T_trix_wclprice_t import *
from strategies_package.U_tsf__ct import *
from strategies_package.U_tsf__t import *
from strategies_package.U_tsf_avg_ct import *
from strategies_package.U_tsf_avg_t import *
from strategies_package.U_tsf_linearReg_ct import *
from strategies_package.U_tsf_linearReg_t import *
from strategies_package.U_tsf_maBo_ct import *
from strategies_package.U_tsf_maBo_t import *
from strategies_package.U_tsf_med_ct import *
from strategies_package.U_tsf_med_t import *
from strategies_package.U_tsf_trix_ct import *
from strategies_package.U_tsf_trix_t import *
from strategies_package.U_tsf_typical_ct import *
from strategies_package.U_tsf_typical_t import *
from strategies_package.U_tsf_wclprice_ct import *
from strategies_package.U_tsf_wclprice_t import *
from strategies_package.V_ultimate_fromInner_ct import *
from strategies_package.V_ultimate_fromInner_t import *
from strategies_package.V_ultimate_fromOuter_ct import *
from strategies_package.V_ultimate_fromOuter_t import *
from strategies_package.V_ultimate_htTrend_fromInner_ct import *
from strategies_package.V_ultimate_htTrend_fromInner_t import *
from strategies_package.V_ultimate_htTrend_fromOuter_ct import *
from strategies_package.V_ultimate_htTrend_fromOuter_t import *
from strategies_package.V_ultimate_linearReg_ct import *
from strategies_package.V_ultimate_linearReg_t import *
from strategies_package.V_ultimate_maBo_ct import *
from strategies_package.V_ultimate_maBo_t import *
from strategies_package.V_ultimate_trix_ct import *
from strategies_package.V_ultimate_trix_t import *
from strategies_package.V_ultimate_tsf_ct import *
from strategies_package.V_ultimate_tsf_t import *
from strategies_package.W_willR_fromInner_ct import *
from strategies_package.W_willR_fromInner_t import *
from strategies_package.W_willR_fromOuter_ct import *
from strategies_package.W_willR_fromOuter_t import *
from strategies_package.W_willR_htTrend_fromInner_ct import *
from strategies_package.W_willR_htTrend_fromInner_t import *
from strategies_package.W_willR_htTrend_fromOuter_ct import *
from strategies_package.W_willR_htTrend_fromOuter_t import *
from strategies_package.W_willR_linearReg_ct import *
from strategies_package.W_willR_linearReg_t import *
from strategies_package.W_willR_maBo_ct import *
from strategies_package.W_willR_maBo_t import *
from strategies_package.W_willR_trix_ct import *
from strategies_package.W_willR_trix_t import *
from strategies_package.W_willR_tsf_ct import *
from strategies_package.W_willR_tsf_t import *
from strategies_package.Z_3InsideUpDown import *
from strategies_package.Z_3LineStrike import *
from strategies_package.Z_3Outside import *
from strategies_package.Z_3whiteSoldiers import *
from strategies_package.Z_abandonedBaby import *
from strategies_package.Z_beltHold import *
from strategies_package.Z_doji import *
from strategies_package.Z_dragonFly import *
from strategies_package.Z_engulfing import *
from strategies_package.Z_hammer import *
from strategies_package.Z_harami import *
from strategies_package.Z_haramiCross import *
from strategies_package.Z_highWave import *
from strategies_package.Z_hikkake import *
from strategies_package.Z_hikkakeMod import *
from strategies_package.Z_longDoji import *
from strategies_package.Z_longLine import *
from strategies_package.Z_marubozu import *
from strategies_package.Z_marubozuClosing import *
from strategies_package.Z_richshawMan import *
from strategies_package.Z_shortLine import *
from strategies_package.Z_spinningTop import *
